linters:
  enable-all: true
  disable:
    # annoying
    - gocyclo
    - tagliatelle
    - nestif
    - gocognit
    - varnamelen
    - nonamedreturns
    - testpackage
    - goconst
    - gochecknoinits
    - gomnd
    - mnd
    - inamedparam
    - err113
    - godox
    - exhaustruct
    - cyclop
    - ireturn
    - funlen
    - gomoddirectives # need replacements for wasip1
    - execinquery # deprecated
    - exportloopref # deprecated
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake

  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
      - name: unused-receiver
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/open-policy-agent/opa)
      - prefix(github.com/styrainc/regal)
      - blank
      - dot

  depguard:
    rules:
      main:
        deny:
          - pkg: "gopkg.in/yaml.v2"
            desc: use yaml.v3 only

issues:
  exclude-dirs:
    - internal/lsp/opa
