linters:
  enable-all: true
  disable:
    # annoying
    - gocyclo
    - tagliatelle
    - nestif
    - gocognit
    - varnamelen
    - nonamedreturns
    - testpackage
    - goconst
    - gochecknoinits
    - mnd
    - inamedparam
    - err113
    - godox
    - exhaustruct
    - cyclop
    - ireturn
    - funlen
    - gomoddirectives # need replacements for wasip1
    - tenv # deprecated
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
      - name: unused-receiver
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/open-policy-agent/opa)
      - prefix(github.com/styrainc/roast)
      - prefix(github.com/styrainc/regal)
      - blank
      - dot
  depguard:
    rules:
      main:
        deny:
          - pkg: "gopkg.in/yaml.v2"
            desc: use yaml.v3 only
  govet:
    enable-all: true
    disable:
      - shadow
      # this is nice, but it doesn't seem possible to disable
      # this for tests? definitely don't want this in tests
      - fieldalignment

issues:
  exclude-dirs:
    - internal/lsp/opa
  exclude-files:
    # For whatever reason, the exclude-dirs setting isn't honored when
    # golangci-lint is targeting one of these files *specifically* rather
    # than whole whole workspace / directory. This happens when opening up
    # one of these files in VS Code, which will have the linter complain
    # loudly. Hopefully this workaround can be removed in the future.
    - oracle.go
    - scanner.go
    - tokens.go
