linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - inamedparam
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    # does not work with generics (yet)
    - rowserrcheck
    - wastedassign
    # annoying
    - goerr113
    - varnamelen
    - nonamedreturns
    - testpackage
    - gochecknoinits
    - gomnd
    - godox
    - exhaustruct
    - cyclop
    - ireturn
    - funlen
    - nolintlint
    - depguard
    - gomoddirectives # need replacements for wasip1
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/open-policy-agent/opa)
      - prefix(github.com/styrainc/regal)
      - blank
      - dot
