package encoding

const (
	strLocation         = "location"
	strScope            = "scope"
	strTitle            = "title"
	strDescription      = "description"
	strEntrypoint       = "entrypoint"
	strOrganizations    = "organizations"
	strRelatedResources = "related_resources"
	strAuthors          = "authors"
	strSchemas          = "schemas"
	strCustom           = "custom"
	strPackage          = "package"
	strImports          = "imports"
	strRules            = "rules"
	strComments         = "comments"
	strAnnotations      = "annotations"
	strHead             = "head"
	strRef              = "ref"
	strArgs             = "args"
	strAssign           = "assign"
	strElse             = "else"
	strTerm             = "term"
	strBody             = "body"
	strText             = "text"
	strPath             = "path"
	strType             = "type"
	strValue            = "value"
	strKey              = "key"
	strDefault          = "default"
	strDomain           = "domain"
	strNegated          = "negated"
	strWith             = "with"
	strGenerated        = "generated"
	strTerms            = "terms"
	strAlias            = "alias"
	strSymbols          = "symbols"
	strTarget           = "target"
)
